version: '3'

services:
  flyway:
    image: gsengun/flyway-postgres
    command: 'postgresdev 5432 postgres password pgdev public'
    volumes:
      - ./flywayMigrations:/flyway/sql
    depends_on:
      - postgresdev
  users:
    image: anapsix/alpine-java:8_jdk_unlimited
    ports:
      - '8090:8090'
    working_dir: /back-end-users
    volumes:
      - .:/back-end-users
    command: './gradlew bootRun'
    depends_on:
      - postgresdev
    environment:
      - GRADLE_USER_HOME=cache
      - SPRING_PROFILES_ACTIVE=dev
  postgresdev:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pgdev
  react:
    image: node
    ports:
      - '3000:3000'
    command: 'npm start'
    working_dir: /user-interface
    volumes:
      - ./user-interface:/user-interface
    depends_on:
      - users