version: '3'

services:
  eureka:
    image: anapsix/alpine-java:8_jdk_unlimited
    ports:
      - '8761:8761'
    working_dir: /eureka-server
    volumes:
      - ./eureka-server:/eureka-server
    command: './gradlew bootRun'
    environment:
      - GRADLE_USER_HOME=cache
      - SPRING_PROFILES_ACTIVE=dev
  api-gateway:
    image: anapsix/alpine-java:8_jdk_unlimited
    ports:
      - '8080:8080'
    working_dir: /api-gateway
    volumes:
      - ./api-gateway:/api-gateway
    depends_on:
      - eureka
    command: './gradlew bootRun'
    environment:
      - GRADLE_USER_HOME=cache
      - SPRING_PROFILES_ACTIVE=dev
  flyway:
    image: gsengun/flyway-postgres
    command: 'postgresdev 5432 postgres password pgdev public'
    volumes:
      - ./flywayMigrations:/flyway/sql
    depends_on:
      - postgresdev
  users:
    image: anapsix/alpine-java:8_jdk_unlimited
    ports:
      - '8090:8090'
    working_dir: /users-api
    volumes:
      - ./users-api:/users-api
    command: './gradlew bootRun'
    depends_on:
      - eureka
      - postgresdev
    environment:
      - GRADLE_USER_HOME=cache
      - SPRING_PROFILES_ACTIVE=dev
  posts:
    image: anapsix/alpine-java:8_jdk_unlimited
    ports:
      - '8091:8091'
    working_dir: /posts-api
    volumes:
      - ./posts-api:/posts-api
    command: './gradlew bootRun'
    depends_on:
      - eureka
      - postgresdev
    environment:
      - GRADLE_USER_HOME=cache
      - SPRING_PROFILES_ACTIVE=dev
  postgresdev:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pgdev
  react:
    image: node
    ports:
      - '3000:3000'
    command: 'npm start'
    working_dir: /user-interface
    volumes:
      - ./user-interface:/user-interface
    depends_on:
      - users
    environment:
      - REACT_APP_USERS_API=http://localhost:8080/users
      - REACT_APP_POSTS_API=http://localhost:8080/posts